In [ ]:
#Numpy 
#수학과데이터 분석을 쉽게 할수 있도록 도와주는 라이브러리
#ndArray
#숫자를 여러 차원으로 저장할 수 있는 배열

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#1차원 배열
arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
#2차원 배열
arr3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                [[1, 2, 3, 4], [5, 6, 7, 8]]])
#3차원 배열
print(type(a))
print(f"a + b = {a+b}")
print(a + 1)
print(arr2.shape) #2줄에 각 4칸
print(arr3.shape) #2장 각 장마다 2줄 각 줄에 4칸

#size 배열 요소의 총 개수
print(arr2.size)
print(arr3.size)

#dtype 배열 요소의 타입
print(arr2.dtype)

#data 배열의 실제 데이터가 저장된 메모리 주소
print(arr2.data)

#전치행열
#nbArray T : 전치 행렬
print('원래 배열')
print(arr2)
print('전치 배열')
print(arr2.T)

#flatten()
#배열 펼치기
print(f"{arr2.flatten()}\n")

#ndArray.reshape()
#배열 모양 바꾸기
print('배열 모양 바꾸기 전')
arr_re = arr2.flatten()
print(f"{arr_re}\n")
print('배열 모양 바꾸기 후')
print(f"{arr_re.reshape(2,4)}\n")

#mean 평균 구하기

#axis
#axis = 0 세로방향의 합
#axis = 1 가로방향의 합

print(arr2.mean())

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("전체 최솟값 = ", arr.min())
print("전체 최댓값 = ", arr.max())
print("열방향 최솟값 = ",arr.min(axis = 0))


In [ ]:
import numpy as np

# .zeros(n, n)
# n열 n행인 0으로 이루어진 배열 생성
arr_zeros = np.zeros((4,4))
print(f"{arr_zeros}\n")

# .ones(x, y, z)
# x층 y열 z행인 1로 이루어진 배열 생성
arr_ones = np.ones((2, 3, 4))
print(f"{arr_ones}\n")

# .full()

# _like
# 다른 배열의 shape을 기준으로 새 배열을 생성
# 원본과 똑같이 안전하게 생성 가능함

arr_reple = np.zeros_like(arr_zeros)
print(f"{arr_reple}\n")

In [2]:
import numpy as np
# .random
# 다양한 랜덤 난수 생성
# randint(시작값, 끝값, size)
arr_ran = np.random.randint(1, 100, (2,2,2))
print(f"{arr_ran}\n")

#seed
#난수 생성 초기 생성 기준을 잡음
#시드 값을 기준으로 생성
np.random.seed(1)
arr_seed = np.random.randint(1, 100, 4)
print(arr_seed)



[[[76  6]
  [80 65]]

 [[17  2]
  [77 72]]]

[38 13 73 10]


In [ ]:
import numpy as np

# 인덱싱
# 특정위치에서 특정 하나의 값을 가져오는 방법

# 슬라이싱
# 일정  범위를 잘라서 여러값을 가져오는 방법

arr1 = np.random.randint(1, 100, (2, 5, 5))
print(f"생성 배열")
print(f"{arr1}\n")
print(f"인덱싱 결과 = {arr1[1, 1, 1]}\n")
print(f"슬라이싱 결과 = {arr1[1:2, 1:3, 2:4]}\n")
print(f"Fancy 인덱싱 결과\n {arr1[0, 1, 3], arr1[1, 1, 2]}")

#논리값 인덱싱


생성 배열
[[[79 76 59 43 27]
  [22 59 17 93 38]
  [12 23  7 97 15]
  [88 76 36 64 33]
  [92 50  1 23 98]]

 [[71 37 19 28 29]
  [53 95 51 47  8]
  [86 17 30 12 62]
  [15 31  9 41 49]
  [31 24 67 93 65]]]

인덱싱 결과 = 95

슬라이싱 결과 = [[[51 47]
  [30 12]]]

Fancy 인덱싱 결과
 (np.int32(93), np.int32(51))
